In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("IMDB_Data.csv")
df # importing dataset in datafeame

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),-2019.0,109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,-2021.0,90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,-2019.0,110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,-2010.0,105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali
...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,-1988.0,NaN,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,Zulmi,-1999.0,129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15506,Zulmi Raj,-2005.0,NaN,Action,NaN,NaN,Kiran Thej,Sangeeta Tiwari,NaN,NaN
15507,Zulmi Shikari,-1988.0,NaN,Action,NaN,NaN,NaN,NaN,NaN,NaN
15508,Zulm-O-Sitam,-1998.0,130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [3]:
df

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),-2019.0,109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,-2021.0,90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,-2019.0,110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,-2010.0,105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali
...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,-1988.0,NaN,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,Zulmi,-1999.0,129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15506,Zulmi Raj,-2005.0,NaN,Action,NaN,NaN,Kiran Thej,Sangeeta Tiwari,NaN,NaN
15507,Zulmi Shikari,-1988.0,NaN,Action,NaN,NaN,NaN,NaN,NaN,NaN
15508,Zulm-O-Sitam,-1998.0,130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [4]:
df.isnull().sum()

Name           0
Year         529
Duration    8268
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2385
Actor 3     3153
dtype: int64

In [5]:
Rating=df['Rating'].mean()
Rating

5.842757923980301

In [6]:
df['Rating'].fillna(Rating,inplace=True)
df.dropna()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),-2019.0,109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,-2019.0,110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,-1997.0,147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,-2005.0,142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,-2012.0,82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...,...,...
15493,Zubaan,-2015.0,115 min,Drama,6.1,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana
15494,Zubeidaa,-2001.0,153 min,"Biography, Drama, History",6.2,"1,496",Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee
15503,Zulm Ki Zanjeer,-1989.0,125 min,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
15505,Zulmi,-1999.0,129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15508,Zulm-O-Sitam,-1998.0,130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [7]:
# Drop multiple columns from a DataFrame
df.drop(['Name'], inplace=True,axis = 1)

In [8]:
df

,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,NaN,NaN,Drama,5.842758,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,-2019.0,109 min,Drama,7.000000,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,-2021.0,90 min,"Drama, Musical",5.842758,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,-2019.0,110 min,"Comedy, Romance",4.400000,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,-2010.0,105 min,Drama,5.842758,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali
...,...,...,...,...,...,...,...,...,...
15504,-1988.0,NaN,Action,4.600000,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,-1999.0,129 min,"Action, Drama",4.500000,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15506,-2005.0,NaN,Action,5.842758,NaN,Kiran Thej,Sangeeta Tiwari,NaN,NaN
15507,-1988.0,NaN,Action,5.842758,NaN,NaN,NaN,NaN,NaN
15508,-1998.0,130 min,"Action, Drama",6.200000,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [9]:
df.dropna(inplace=True)

In [10]:
df

,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,-2019.0,109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,-2019.0,110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,-1997.0,147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,-2005.0,142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,-2012.0,82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...,...
15493,-2015.0,115 min,Drama,6.1,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana
15494,-2001.0,153 min,"Biography, Drama, History",6.2,"1,496",Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee
15503,-1989.0,125 min,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
15505,-1999.0,129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15508,-1998.0,130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [11]:
y= df['Rating']
x1= df.iloc[:,:3] 
x2=df.iloc[:,4:]

x = pd.concat([x1, x2], axis=1, )
x

,Year,Duration,Genre,Votes,Director,Actor 1,Actor 2,Actor 3
1,-2019.0,109 min,Drama,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,-2019.0,110 min,"Comedy, Romance",35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,-1997.0,147 min,"Comedy, Drama, Musical",827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,-2005.0,142 min,"Drama, Romance, War","1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,-2012.0,82 min,"Horror, Mystery, Thriller",326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...
15493,-2015.0,115 min,Drama,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana
15494,-2001.0,153 min,"Biography, Drama, History","1,496",Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee
15503,-1989.0,125 min,"Action, Crime, Drama",44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
15505,-1999.0,129 min,"Action, Drama",655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15508,-1998.0,130 min,"Action, Drama",20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

#import model
from sklearn.preprocessing import LabelEncoder
#init lable encoder
le=LabelEncoder()

#transfer output
for i in df :
    df[i] = le.fit_transform(df[i])

In [20]:
x['Year'] = x['Year'].apply(lambda x: abs(x))
x['Duration'] = x['Duration'].str.replace(' min', '', regex=False)

In [17]:
# Extract numeric values using regular expression
x

,Year,Duration,Genre,Votes,Director,Actor 1,Actor 2,Actor 3
1,2019.0,109,Drama,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,2019.0,110,"Comedy, Romance",35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,1997.0,147,"Comedy, Drama, Musical",827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,2005.0,142,"Drama, Romance, War","1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,2012.0,82,"Horror, Mystery, Thriller",326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...
15493,2015.0,115,Drama,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana
15494,2001.0,153,"Biography, Drama, History","1,496",Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee
15503,1989.0,125,"Action, Crime, Drama",44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
15505,1999.0,129,"Action, Drama",655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15508,1998.0,130,"Action, Drama",20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [67]:
#import model
from sklearn.preprocessing import LabelEncoder
#init lable encoder
le=LabelEncoder()

#transfer output
x['Genre'] = le.fit_transform(x['Genre'])
x['Director'] = le.fit_transform(x['Director'])
x['Actor 1'] = le.fit_transform(x['Actor 1'])
x['Actor 2'] = le.fit_transform(x['Actor 2'])
x['Actor 3'] = le.fit_transform(x['Actor 3'])
x['Votes'] = le.fit_transform(x['Votes'])
x['Year'] = x['Year'].astype(int)
x['Duration'] = x['Duration'].astype(int)

In [68]:
x

       Year  Duration  Genre  Votes  Director  Actor 1  Actor 2  Actor 3
1      2019       109    228   1841       629     1348     2268      317
3      2019       110    183   1163      1333     1194      717     2145
5      1997       147    156   1890      1528      377       75     2042
6      2005       142    288     36      2041      690     1110     2519
8      2012        82    319   1132       135     1929     1173     1010
...     ...       ...    ...    ...       ...      ...      ...      ...
15493  2015       115    228   1310      1221     1856     1798     1612
15494  2001       153    132    182      2056      760     1616     1181
15503  1989       125     28   1346      1790      404      752     1682
15505  1999       129     38   1679      1023      112     2161      312
15508  1998       130     38    792       894      466      751      301

[5653 rows x 8 columns]

In [69]:
y

1        7.0
3        4.4
5        4.7
6        7.4
8        5.6
        ...
15493    6.1
15494    6.2
15503    5.8
15505    4.5
15508    6.2
Name: Rating, Length: 5653, dtype: float64

In [70]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.30,random_state=1)

In [71]:
from sklearn.linear_model import LinearRegression

In [72]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=1)
model = LinearRegression()
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)
train=model.score(xtrain,ytrain)
test=model.score(xtest,ytest)
print(f"Training Accuracy = {train}")
print(f"Testing Accuracy = {test}")

Training Accuracy = 0.06020009241361424
Testing Accuracy = 0.05717373657202318

In [73]:

from sklearn.metrics import r2_score

In [74]:

# Calculate the R^2 score
r2 = r2_score(ytest, ypred)
r2

0.05717373657202318

In [75]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5653 entries, 1 to 15508
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Year      5653 non-null   int32
 1   Duration  5653 non-null   int32
 2   Genre     5653 non-null   int64
 3   Votes     5653 non-null   int64
 4   Director  5653 non-null   int64
 5   Actor 1   5653 non-null   int64
 6   Actor 2   5653 non-null   int64
 7   Actor 3   5653 non-null   int64
dtypes: int32(2), int64(6)
memory usage: 353.3 KB

In [78]:
y

1        7.0
3        4.4
5        4.7
6        7.4
8        5.6
        ...
15493    6.1
15494    6.2
15503    5.8
15505    4.5
15508    6.2
Name: Rating, Length: 5653, dtype: float64

In [79]:

    # Get user inputs
    Year = int(input('Enter Year: '))
    Duration = int(input('Enter Duration (in minutes): '))
    Genre = int(input('Enter Genre): ')) 
    Votes = int(input('Enter Votes: '))
    Director = int(input('Enter Director: '))
    Actor1 = int(input('Enter Actor 1: '))  
    Actor2 = int(input('Enter Actor 2: ')) 
    Actor3 = int(input('Enter Actor 3: ') )
res = model.predict([[Year, Duration, Genre, Votes, Director, Actor1, Actor2, Actor3]])
print("Predicted Rating :" , res)

Enter Year:  2019
Enter Duration (in minutes):  100
Enter Genre):  200
Enter Votes:  1700
Enter Director:  200
Enter Actor 1:  1000
Enter Actor 2:  1000
Enter Actor 3:  300

Predicted Rating : [5.70445244]

C:\Users\Laptop_User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(